name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: "write"
      pull-requests: "write"
      id-token: "write" # Required for coverage report updates

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: maven
        server-id: central-publish
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_PASSWORD

    - name: Build with Maven
      run: mvn -B clean install
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        path: |
          ${{ github.workspace }}/target/site/kover/report.xml
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 90
        min-coverage-changed-files: 90
        coverage-counter-type: LINE

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
